[package]
name = "hiddenpng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
aes = "0.7.0"
block-modes = "0.8.1"
block-padding = "0.3.2"
typenum = "1.16.0"
generic-array = "0.14.6"
